### ISSUE TITLE
Password for LDAP/Gluu should only be presented once

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#52]
The password has to be the same, so allowing multiple locations for entry may cause problems if the user changes passwords.

**Comment by tecoholic** [comment]
This ticket is a little bit unclear. Presently the fix enforces same admin passwords for LDAP servers in all the hosts. I am afraid the fix is dangerous and restricting. Hypothetical situation for test case:

**Setup:** There is 3 server cluster setup. One of the hosts' LDAP gets breached.

**Case 1: Enforcing same password across cluster** Apart from the obvious data theft/loss suffered. The entire cluster has to be shutdown and the setup provides no room for isolation of affected server as all the servers can now be breached with the same credentials.

**Case 2: Allowing for different LDAP passwords for different hosts** There is the inevitable data loss. Since only one host has been breached, it alone can be removed from the cluster and the breach investigated while the rest of the cluster can function. This provides room fro isolation of the affected system.

If I were an admin, I would want to have different passwords for the servers.

**Comment by tecoholic** [comment]
Moved to #54
