### ISSUE TITLE
Run multiple tasks on different servers

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#68]
![image](https://user-images.githubusercontent.com/30447907/32025813-2b792e88-b9a7-11e7-88d3-e4e3b807033e.png)
Here is one example of a task that should be running simultaneously on all servers to save time. Also consider the same for installing Gluu after the primary is installed.

**Comment by afroDC** [comment]
![image](https://user-images.githubusercontent.com/30447907/32025924-9bebf3da-b9a7-11e7-877f-0e9698b92fbf.png)
Another task that could be run simultaneously across machines.

**Comment by afroDC** [comment]
![image](https://user-images.githubusercontent.com/30447907/32026784-57c3a550-b9ab-11e7-921d-1a0fa8424e90.png)

![image](https://user-images.githubusercontent.com/30447907/32026792-5f882cca-b9ab-11e7-83a2-793c02abb6cf.png)

After primary server is installed, User should be able to simultaneously install Gluu servers. As it is now, it installs one at a time.

**Comment by tecoholic** [comment]
I think this is a non-issue or at least an enhancement that is a luxury. Here are the reasons:
* The setup actions are going to be run *infrequently* (probably a handful times in a year) by the admin so the long execution time is something that won't matter much.
* Moving from sequential execution to parallel execution would make the code base more complex, a cost that I don't see justifying the outcome at this point (maybe in the future).
* Maybe this is more visible to the testers because of the frequent usage of the interface.

**Comment by afroDC** [comment]
Arun,

I've tagged it as an enhancement to improve user experience. I don't think it's a rush or essential, but would improve ease of use. We can keep pushing it until we have spare time and most things are finished.
