### ISSUE TITLE
Logging interface for Gluu modules

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/cluster-mgr#69]
Develop an interface to pull logs from all servers and present them in a manageable way.

**Comment by iromli** [comment]
From my point of view, this issue involve 2 things:

1. Configure and install required tools in remote servers.
2. Using the UI.

For point 2, I'm thinking that instead of adding new UI, why don't we use existing tools from logging management stack (ELK/InfluxDB)? By using this approach, we can use their advance UI and reduce the code (and potential bugs) in Cluster Manager.

**Comment by afroDC** [comment]
So would installing the other logging service, does a user open that program separately? How would that work in practice.

**Comment by iromli** [comment]
Merged to `master` branch

**Comment by afroDC** [comment]
Working
